### ISSUE TITLE
mocker start 启动成功，但是提示cmd有问题

### ISSUE THREAD

**Issue by caozhiming20** [wenlonghuo/xmocker-cli#11]
{ Error: spawn C:\windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\windows\\system32\\cmd.exe',
  path: 'C:\\windows\\system32\\cmd.exe',

环境变量我也重新配了，node 版本 10.16.3

**Comment by wenlonghuo** [comment]
这个应该是环境的问题，Nodejs 要么环境变量没有配置好，要么是没有打开 cmd 的权限。可以参见这个问题： https://stackoverflow.com/questions/38458118/nodejs-error-spawn-c-windows-system32-cmd-exe-enoent

**Comment by caozhiming20** [comment]
cmd 的环境变量已经在Path 中加了%SystemRoot%\system32\cmd.exe，在CMD 中输入Path：cmd 的路径也出现了；
权限：我在cmd 属性->安全 里面将系统用户的权限也都改成完全控制。
问题还是没解决。是我改的方法有问题吗？

**Comment by wenlonghuo** [comment]
那应该是权限问题，以管理员身份开启命令行试试
